import {
  AppSettings,
  PublicationPreset,
  Snippet,
  TextPreset,
  Theme,
  ThemeDefinition,
  ThemeConfig,
} from "./types";
import { createPublicationPreset } from "./services/publication-style";

const THEME_BG_CLASS = "bg-[var(--ml-bg)]";
const THEME_FG_CLASS = "text-[var(--ml-fg)]";
const THEME_UI_CLASS = "bg-[var(--ml-ui)]";
const THEME_BORDER_CLASS = "border-[var(--ml-border)]";
const THEME_EDITOR_BG_CLASS = "bg-[var(--ml-editor-bg)]";
const THEME_EDITOR_FG_CLASS = "text-[var(--ml-editor-fg)]";
const THEME_ACCENT_CLASS = "text-[var(--ml-accent)]";

export const THEMES: Record<Theme, ThemeConfig> = {
  [Theme.Coffee]: {
    bg: THEME_BG_CLASS,
    bgHex: "#2b231f",
    fg: THEME_FG_CLASS,
    fgHex: "#f8f1e8",
    ui: THEME_UI_CLASS,
    uiHex: "#3a2f29",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#6a5448",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#2b231f",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#f8f1e8",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#f4c68f",
    prose: "prose-invert prose-stone",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Light]: {
    bg: THEME_BG_CLASS,
    bgHex: "#ffffff",
    fg: THEME_FG_CLASS,
    fgHex: "#0f172a",
    ui: THEME_UI_CLASS,
    uiHex: "#f9fafb",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#e5e7eb",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#ffffff",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#0f172a",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#4f46e5",
    prose: "prose-slate",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'Fira Code', 'JetBrains Mono', monospace",
  },
  [Theme.Dark]: {
    bg: THEME_BG_CLASS,
    bgHex: "#16191e",
    fg: THEME_FG_CLASS,
    fgHex: "#f4f4f5",
    ui: THEME_UI_CLASS,
    uiHex: "#1d2229",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#2c3440",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#16191e",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#f4f4f5",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#7dd3fc",
    prose: "prose-invert",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Forest]: {
    bg: THEME_BG_CLASS,
    bgHex: "#17241b",
    fg: THEME_FG_CLASS,
    fgHex: "#e8fbe9",
    ui: THEME_UI_CLASS,
    uiHex: "#203124",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#3c6b48",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#17241b",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#e8fbe9",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#90f0a8",
    prose: "prose-invert prose-green",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'Cascadia Code', 'JetBrains Mono', monospace",
  },
  [Theme.Golden]: {
    bg: THEME_BG_CLASS,
    bgHex: "#f4d49a",
    fg: THEME_FG_CLASS,
    fgHex: "#1e1308",
    ui: THEME_UI_CLASS,
    uiHex: "#e7be73",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#6b4b16",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#f4d49a",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#1e1308",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#2a1808",
    prose: "prose-amber",
    uiFont: "'Merriweather Sans', 'Segoe UI', sans-serif",
    editorFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
  [Theme.Midnight]: {
    bg: THEME_BG_CLASS,
    bgHex: "#111827",
    fg: THEME_FG_CLASS,
    fgHex: "#eef2ff",
    ui: THEME_UI_CLASS,
    uiHex: "#0b1220",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#24344e",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#111827",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#eef2ff",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#8fb5ff",
    prose: "prose-invert prose-indigo",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Neomatrix]: {
    bg: THEME_BG_CLASS,
    bgHex: "#040b04",
    fg: THEME_FG_CLASS,
    fgHex: "#8afcc7",
    ui: THEME_UI_CLASS,
    uiHex: "#061207",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#1b5a33",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#040b04",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#8afcc7",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#57ff9e",
    prose: "prose-invert prose-green",
    uiFont: "'Chakra Petch', 'Segoe UI', sans-serif",
    editorFont: "'Share Tech Mono', 'Cascadia Code', monospace",
  },
  [Theme.Nord]: {
    bg: THEME_BG_CLASS,
    bgHex: "#2E3440",
    fg: THEME_FG_CLASS,
    fgHex: "#ECEFF4",
    ui: THEME_UI_CLASS,
    uiHex: "#262f40",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#425066",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#2E3440",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#ECEFF4",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#88C0D0",
    prose: "prose-invert prose-blue",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Sepia]: {
    bg: THEME_BG_CLASS,
    bgHex: "#f2e6c5",
    fg: THEME_FG_CLASS,
    fgHex: "#2d2417",
    ui: THEME_UI_CLASS,
    uiHex: "#e8d7ad",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#b99f63",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#f2e6c5",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#2d2417",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#8d5f12",
    prose: "prose-stone",
    uiFont: "'Merriweather Sans', 'Segoe UI', sans-serif",
    editorFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
  [Theme.Synthwave]: {
    bg: THEME_BG_CLASS,
    bgHex: "#221833",
    fg: THEME_FG_CLASS,
    fgHex: "#fef3ff",
    ui: THEME_UI_CLASS,
    uiHex: "#2e1f45",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#8a39d3",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#221833",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#fef3ff",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#ff89cf",
    prose: "prose-invert prose-pink",
    uiFont: "'Exo 2', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Terminal]: {
    bg: THEME_BG_CLASS,
    bgHex: "#000000",
    fg: THEME_FG_CLASS,
    fgHex: "#87ffa5",
    ui: THEME_UI_CLASS,
    uiHex: "#050505",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#1c4728",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#000000",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#87ffa5",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#5bffa0",
    prose: "prose-invert prose-green",
    uiFont: "'Chakra Petch', 'Segoe UI', sans-serif",
    editorFont: "'Share Tech Mono', 'Cascadia Code', monospace",
  },
  [Theme.Firenight]: {
    bg: THEME_BG_CLASS,
    bgHex: "#1b0f0d",
    fg: THEME_FG_CLASS,
    fgHex: "#ffe1bf",
    ui: THEME_UI_CLASS,
    uiHex: "#2a1713",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#8a4c31",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#1b0f0d",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#ffe1bf",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#ffb86c",
    prose: "prose-invert prose-amber",
    uiFont: "'Merriweather Sans', 'Segoe UI', sans-serif",
    editorFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
};

export const DEFAULT_THEME_LIBRARY: ThemeDefinition[] = Object.values(Theme).map((themeId) => ({
  id: themeId,
  name: themeId,
  builtIn: true,
  baseThemeId: themeId,
  config: THEMES[themeId],
}));

export function createDefaultThemeLibrary(): ThemeDefinition[] {
  return DEFAULT_THEME_LIBRARY.map((theme) => ({
    ...theme,
    config: { ...theme.config },
  }));
}

export const DEFAULT_SHORTCUTS: Record<string, string> = {
  "file-new": "Ctrl+N",
  "file-open": "Ctrl+O",
  "file-open-folder": "Ctrl+Shift+O",
  "file-save": "Ctrl+S",
  "file-save-as": "Ctrl+Shift+S",
  "file-export": "Ctrl+E",
  "file-print": "Ctrl+P",
  "edit-undo": "Ctrl+Z",
  "edit-redo": "Ctrl+Y",
  "edit-find": "Ctrl+F",
  "edit-replace": "Ctrl+H",
  "edit-snippets": "Ctrl+J",
  "view-edit": "Ctrl+1",
  "view-split": "Ctrl+2",
  "view-preview": "Ctrl+3",
  "view-zen": "F10",
  "view-toolbar": "Ctrl+T",
  "view-sidebar": "Ctrl+B",
  "help-shortcuts": "F1",
  "view-theme-cycle": "Ctrl+Shift+T",
  "app-settings": "Ctrl+,",
  "app-command-palette": "Ctrl+P",
  "fmt-bold": "Ctrl+Shift+B",
  "fmt-italic": "Ctrl+I",
  "fmt-link": "Ctrl+K",
  "fmt-ul": "Ctrl+Shift+8",
  "fmt-ol": "Ctrl+Shift+7",
  "fmt-task": "Ctrl+Shift+9",
};

export const TEXT_PRESETS: Record<string, TextPreset> = {
  minimalist: {
    id: "minimalist",
    name: "Minimalist",
    description: "Clean sans-serif reading style.",
    fontFamily: "sans",
    proseClass: "prose-slate",
    lineHeight: 1.6,
    components: {
      h1: "font-sans font-bold tracking-tight",
      h2: "font-sans font-semibold tracking-tight",
      p: "font-sans leading-relaxed",
      img: "rounded-xl shadow-sm",
      blockquote: "border-l-2 border-slate-300 pl-4 italic",
      code: "rounded-md",
      link: "underline decoration-1 underline-offset-2",
    },
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    description: "Serif-focused long-form layout.",
    fontFamily: "serif",
    proseClass: "prose-stone",
    lineHeight: 1.8,
    components: {
      h1: "font-serif font-bold italic tracking-wide",
      h2: "font-serif font-medium",
      p: "font-serif text-lg leading-loose",
      img: "rounded-sm shadow-md",
      blockquote: "border-l-4 border-stone-400 pl-6 italic font-serif text-xl",
      code: "rounded",
      link: "decoration-2 underline-offset-4",
    },
  },
  technical: {
    id: "technical",
    name: "Technical",
    description: "Documentation-first technical style.",
    fontFamily: "mono",
    proseClass: "prose-neutral",
    lineHeight: 1.5,
    components: {
      h1: "font-mono font-bold uppercase tracking-tighter",
      h2: "font-mono font-bold border-b pb-2",
      p: "font-sans text-base",
      img: "rounded-none border-2 border-gray-200",
      blockquote:
        "bg-gray-100 dark:bg-gray-800 p-4 border-l-4 border-gray-500 not-italic font-mono text-sm",
      code: "rounded-sm border border-gray-200 dark:border-gray-700",
      link: "text-blue-600 dark:text-blue-400 hover:underline",
    },
  },
  creative: {
    id: "creative",
    name: "Creative",
    description: "Expressive display style.",
    fontFamily: "sans",
    proseClass: "prose-pink",
    lineHeight: 1.7,
    components: {
      h1: "font-black uppercase tracking-widest decoration-wavy decoration-pink-500 underline",
      h2: "font-bold tracking-wide text-pink-600 dark:text-pink-400",
      p: "font-medium",
      img: "rounded-[2rem] shadow-xl rotate-1 hover:rotate-0 transition-transform",
      blockquote:
        "border-l-8 border-pink-400 pl-6 font-bold text-lg bg-pink-50 dark:bg-pink-900/20 py-2 rounded-r-xl",
      code: "rounded-xl shadow-inner",
      link: "font-bold hover:text-pink-500 transition-colors",
    },
  },
};

export const PUBLICATION_PRESET_DEFAULTS: PublicationPreset[] = [
  {
    ...createPublicationPreset(
      "modern",
      "Modern",
      "Editorial minimalista com leitura limpa e contraste sereno.",
      { bg: "#fbfbf8", text: "#171717", accent: "#374151", muted: "#6b6b61", border: "rgba(23,23,23,0.10)" },
      {
        fontFamily: "'Source Sans 3', 'Inter', 'Segoe UI', sans-serif",
        lineHeight: 1.74,
        bodySize: 17,
        bodyWeight: 410,
        headingWeight: 720,
        tracking: "normal",
      },
      {
        h1: { size: 42, weight: 760, lineHeight: 1.04, letterSpacing: -0.035, marginTop: 2, marginBottom: 22, tone: "text" },
        h2: { size: 28, weight: 700, lineHeight: 1.12, letterSpacing: -0.022, marginTop: 34, marginBottom: 14, tone: "text" },
        h3: { size: 21, weight: 680, lineHeight: 1.18, letterSpacing: -0.005, marginTop: 26, marginBottom: 10, tone: "accent" },
        p: { size: 17, weight: 410, lineHeight: 1.78, marginBottom: 15, tone: "text" },
        list: { size: 16, weight: 410, lineHeight: 1.72, itemGap: 7, indent: 24, markerTone: "muted" },
        blockquote: { paddingX: 20, paddingY: 14, radius: 10, borderWidth: 2, tone: "muted", useBackground: true, italic: false },
        codeInline: { fontSize: 14, paddingX: 6, paddingY: 2, radius: 6, useBackground: true, useBorder: true },
        codeBlock: { fontSize: 13, padding: 18, radius: 10, useBackground: true, useBorder: true },
        table: { headerWeight: 680, cellPaddingX: 14, cellPaddingY: 9, radius: 10, striped: true, dense: false, useBorder: true, captionTone: "muted" },
        image: { radius: 12, margin: 24, useBorder: true, shadow: "none" },
        frontmatterCard: { padding: 16, radius: 10, useBorder: true, useBackground: false, titleWeight: 680 },
      },
      { pagePadding: 42, columnWidth: 760, blockGap: 26, paragraphGap: 15 }
    ),
    builtIn: true,
  },
  {
    ...createPublicationPreset(
      "paper",
      "Paper",
      "Página serifada discreta para textos longos e notas.",
      { bg: "#f7f3ea", text: "#29251e", accent: "#514438", muted: "#74695b", border: "rgba(41,37,30,0.12)" },
      {
        fontFamily: "Georgia, 'Iowan Old Style', 'Times New Roman', serif",
        lineHeight: 1.82,
        bodySize: 18,
        bodyWeight: 400,
        headingWeight: 650,
        tracking: "normal",
      },
      {
        h1: { size: 40, weight: 660, lineHeight: 1.08, letterSpacing: -0.018, marginTop: 2, marginBottom: 24, tone: "text" },
        h2: { size: 27, weight: 620, lineHeight: 1.16, letterSpacing: -0.012, marginTop: 36, marginBottom: 16, tone: "text" },
        h3: { size: 20, weight: 620, lineHeight: 1.24, letterSpacing: 0, marginTop: 28, marginBottom: 10, tone: "accent", italic: true },
        p: { size: 18, weight: 400, lineHeight: 1.82, marginBottom: 16, tone: "text" },
        list: { size: 17, weight: 400, lineHeight: 1.74, itemGap: 7, indent: 26, markerTone: "muted" },
        blockquote: { paddingX: 20, paddingY: 14, radius: 8, borderWidth: 2, tone: "muted", useBackground: true, italic: true },
        codeBlock: { fontSize: 13, padding: 18, radius: 8, useBackground: true, useBorder: true },
        image: { radius: 8, margin: 26, useBorder: true, shadow: "none" },
        table: { headerWeight: 640, cellPaddingX: 14, cellPaddingY: 9, radius: 8, striped: true, dense: false, useBorder: true, captionTone: "muted" },
      },
      { pagePadding: 44, columnWidth: 720, blockGap: 28, paragraphGap: 16 }
    ),
    builtIn: true,
  },
  {
    ...createPublicationPreset(
      "night",
      "Night",
      "Leitura escura editorial com contraste confortável.",
      { bg: "#111318", text: "#e8e3d8", accent: "#c7bca4", muted: "#aaa090", border: "rgba(232,227,216,0.13)" },
      {
        fontFamily: "'Source Sans 3', 'Segoe UI', sans-serif",
        lineHeight: 1.76,
        bodySize: 17,
        bodyWeight: 405,
        headingWeight: 700,
        tracking: "normal",
      },
      {
        h1: { size: 40, weight: 740, lineHeight: 1.06, letterSpacing: -0.025, marginTop: 2, marginBottom: 22, tone: "text" },
        h2: { size: 27, weight: 680, lineHeight: 1.14, letterSpacing: -0.014, marginTop: 34, marginBottom: 14, tone: "text" },
        h3: { size: 20, weight: 650, lineHeight: 1.2, letterSpacing: 0, marginTop: 26, marginBottom: 10, tone: "accent" },
        p: { size: 17, weight: 405, lineHeight: 1.78, marginBottom: 15, tone: "text" },
        list: { size: 16, weight: 405, lineHeight: 1.72, itemGap: 7, indent: 24, markerTone: "accent" },
        blockquote: { paddingX: 20, paddingY: 14, radius: 10, borderWidth: 2, tone: "accent", useBackground: true, italic: false },
        codeInline: { fontSize: 14, paddingX: 6, paddingY: 2, radius: 6, useBackground: true, useBorder: true },
        codeBlock: { fontSize: 13, padding: 18, radius: 10, useBackground: true, useBorder: true },
        image: { radius: 10, margin: 24, useBorder: true, shadow: "none" },
        table: { headerWeight: 680, cellPaddingX: 14, cellPaddingY: 9, radius: 10, striped: true, dense: false, useBorder: true, captionTone: "accent" },
      },
      { pagePadding: 42, columnWidth: 760, blockGap: 26, paragraphGap: 15 }
    ),
    builtIn: true,
  },
  {
    ...createPublicationPreset(
      "magazine",
      "Magazine",
      "Revista minimalista com headings elegantes e ritmo amplo.",
      { bg: "#faf7f1", text: "#171717", accent: "#4b5563", muted: "#78716c", border: "rgba(23,23,23,0.11)" },
      {
        fontFamily: "'Source Sans 3', 'Avenir Next', 'Segoe UI', sans-serif",
        lineHeight: 1.7,
        bodySize: 17,
        bodyWeight: 410,
        headingWeight: 740,
        tracking: "normal",
      },
      {
        h1: { size: 48, weight: 760, lineHeight: 0.98, letterSpacing: -0.04, marginTop: 2, marginBottom: 24, tone: "text" },
        h2: { size: 30, weight: 720, lineHeight: 1.08, letterSpacing: -0.026, marginTop: 38, marginBottom: 14, tone: "text" },
        h3: { size: 20, weight: 680, lineHeight: 1.18, letterSpacing: 0.045, marginTop: 28, marginBottom: 10, tone: "muted", uppercase: true },
        p: { size: 17, weight: 410, lineHeight: 1.76, marginBottom: 15, tone: "text" },
        list: { size: 16, weight: 410, lineHeight: 1.7, itemGap: 7, indent: 24, markerTone: "muted" },
        blockquote: { paddingX: 22, paddingY: 15, radius: 0, borderWidth: 2, tone: "muted", useBackground: false, italic: true },
        codeInline: { fontSize: 14, paddingX: 6, paddingY: 2, radius: 6, useBackground: true, useBorder: true },
        codeBlock: { fontSize: 13, padding: 18, radius: 10, useBackground: true, useBorder: true },
        table: { headerWeight: 700, cellPaddingX: 14, cellPaddingY: 9, radius: 10, striped: true, dense: false, useBorder: true, captionTone: "muted" },
        image: { radius: 10, margin: 28, useBorder: true, shadow: "none" },
      },
      { pagePadding: 46, columnWidth: 790, blockGap: 28, paragraphGap: 15 }
    ),
    builtIn: true,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  language: "pt-BR",
  fontSize: 16,
  lineHeight: 1.6,
  fontFamily: "mono",
  wordWrap: true,
  typewriterMode: false,
  spellCheck: true,
  singleInstance: true,
  autoSave: true,
  autoSaveInterval: 60,
  focusMode: false,
  customShortcuts: DEFAULT_SHORTCUTS,
  presetId: "minimalist",
  publicationPresetId: "modern",
  toolbarPosition: "bottom",
  themeLibrary: createDefaultThemeLibrary(),
  theme: Theme.Golden,
  viewMode: "edit",
  selectionToolbarEnabled: true,
  chromeMode: "unified",
  tabsEnabled: true,
  sidebarEnabled: true,
  sidebarWidth: 260,
  floatingToolbarAnchor: "bottom",
  showToolbarSectionLabels: true,
  toolbarAlwaysShowIcons: true,
  toolbarCompactBreakpoint: 560,
  toolbarDisplayMode: "icon_text",
  toolbarSectionBehavior: "default",
  toolbarSections: {
    files: true,
    system: true,
    editing: true,
  },
  toolbarItems: {
    fileNew: false,
    fileOpen: true,
    fileOpenFolder: true,
    fileSave: true,
    fileExport: true,
    sysFind: true,
    sysSnippets: true,
    sysTheme: true,
    sysSidebar: true,
    sysEdit: true,
    sysSplit: true,
    sysPreview: true,
    sysZen: true,
    sysSettings: true,
    sysFormatMarkdown: true,
    sysMinifyMarkdown: true,
    editBold: true,
    editItalic: true,
    editCode: true,
    editLink: true,
    editImage: true,
    editUL: true,
    editOL: true,
    editTask: true,
  },
  toolbarByAnchor: {
    top: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        sysFormatMarkdown: true,
        sysMinifyMarkdown: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
    bottom: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        sysFormatMarkdown: true,
        sysMinifyMarkdown: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
    left: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        sysFormatMarkdown: true,
        sysMinifyMarkdown: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
    right: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        sysFormatMarkdown: true,
        sysMinifyMarkdown: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
  },
  accordionState: {
    interface: true,
    themes: true,
    toolbar: true,
    behavior: true,
    typography: true,
    shortcuts: false,
    presets: false,
  },
  findReplace: {
    caseSensitive: false,
    wholeWord: false,
    useRegex: false,
  },
  commandPalette: {
    includeActions: true,
    includeOpenTabs: true,
    includeRecentFiles: true,
    includeSnippets: true,
    searchMode: "standard",
    snippetBehavior: "insert",
    closeAfterSelect: true,
    showHints: true,
    maxResults: 18,
  },
};

export const INITIAL_MARKDOWN = `# Mark-Lee

Bem-vindo ao Mark-Lee. Este editor foi atualizado para fluxo com abas, workspace e exportação unificada.

## Comece por aqui

- Abra uma pasta no sidebar para navegar no projeto
- Use \`Ctrl+F\` para buscar/substituir com mais opções
- Exporte seu conteúdo pelo menu único de exportação
`;

export const SNIPPETS: Snippet[] = [
  {
    id: "dev-table",
    name: "Tabela Markdown",
    category: "dev",
    trigger: "tabela",
    icon: "TB",
    content: "| Header 1 | Header 2 |\n|----------|----------|\n| Cell 1   | Cell 2   |",
  },
  {
    id: "dev-code",
    name: "Bloco TypeScript",
    category: "dev",
    trigger: "codigo_ts",
    icon: "CD",
    content: "```ts\n// your code\n```",
  },
  {
    id: "frontend-react-card",
    name: "Componente React Card",
    category: "frontend",
    trigger: "react_card",
    icon: "FE",
    content:
      "```tsx\ntype CardProps = { title: string; body: string };\n\nexport function Card({ title, body }: CardProps) {\n  return (\n    <article className=\"rounded-xl border p-4 shadow-sm\">\n      <h2 className=\"text-lg font-semibold\">{title}</h2>\n      <p className=\"mt-2 text-sm\">{body}</p>\n    </article>\n  );\n}\n```",
  },
  {
    id: "backend-node-endpoint",
    name: "Endpoint Node/Express",
    category: "backend",
    trigger: "endpoint_node",
    icon: "BE",
    content:
      "```ts\nimport { Router } from \"express\";\n\nconst router = Router();\n\nrouter.get(\"/health\", (_req, res) => {\n  res.json({ ok: true, ts: Date.now() });\n});\n\nexport default router;\n```",
  },
  {
    id: "macro-meeting-notes",
    name: "Macro Reuniao",
    category: "macro",
    trigger: "reuniao",
    icon: "MC",
    content:
      "## Reuniao - {{data}}\n\n### Participantes\n- \n\n### Decisoes\n- \n\n### Proximos passos\n- [ ] \n",
  },
  {
    id: "php-class",
    name: "Classe PHP",
    category: "php",
    trigger: "php_classe",
    icon: "PH",
    content:
      "```php\n<?php\n\ndeclare(strict_types=1);\n\nfinal class UserService\n{\n    public function findById(int $id): array\n    {\n        return ['id' => $id, 'name' => 'Mark'];\n    }\n}\n```",
  },
  {
    id: "java-service",
    name: "Service Java",
    category: "java",
    trigger: "java_service",
    icon: "JV",
    content:
      "```java\npublic class UserService {\n  public String health() {\n    return \"ok\";\n  }\n}\n```",
  },
  {
    id: "python-dataclass",
    name: "Dataclass Python",
    category: "python",
    trigger: "python_dataclass",
    icon: "PY",
    content:
      "```python\nfrom dataclasses import dataclass\n\n@dataclass(slots=True)\nclass Person:\n    name: str\n    email: str\n```",
  },
  {
    id: "editorial-article-structure",
    name: "Estrutura Editorial",
    category: "editorial",
    trigger: "editorial_artigo",
    icon: "ED",
    content:
      "# Titulo\n\n## Gancho\n\n## Contexto\n\n## Argumento principal\n\n## Fechamento\n",
  },
  {
    id: "shopping-list",
    name: "Lista de Compras",
    category: "lista_compras",
    trigger: "lista_compras",
    icon: "LC",
    content:
      "## Lista de compras\n\n- [ ] Arroz\n- [ ] Feijao\n- [ ] Cafe\n- [ ] Leite\n- [ ] Frutas\n",
  },
  {
    id: "dados-pessoais",
    name: "Dados Pessoais",
    category: "dados_pessoais",
    trigger: "dados_pessoais",
    icon: "DP",
    content:
      "Nome completo: \nData de nascimento: \nCPF: \nRG: \nEndereco: \nCidade/UF: \nCEP: \n",
  },
  {
    id: "contato-card",
    name: "Contato",
    category: "contato",
    trigger: "contato",
    icon: "CT",
    content:
      "Nome: \nEmpresa: \nCargo: \nEmail: \nTelefone: \nLinkedIn: \n",
  },
  {
    id: "task",
    name: "Task List",
    category: "dev",
    trigger: "tarefas",
    icon: "TS",
    content: "- [ ] Task 1\n- [ ] Task 2\n- [x] Done",
  },
  {
    id: "callout",
    name: "Callout",
    category: "editorial",
    trigger: "chamada",
    icon: "NT",
    content: "> **Note:** Important information here.",
  },
  {
    id: "image",
    name: "Image",
    category: "frontend",
    trigger: "imagem_md",
    icon: "IM",
    content: "![Alt text](./image.png)",
  },
  {
    id: "link",
    name: "Link",
    category: "dev",
    trigger: "link_md",
    icon: "LK",
    content: "[Link text](https://example.com)",
  },
];
