import {
  AppSettings,
  PublicationPreset,
  Snippet,
  TextPreset,
  Theme,
  ThemeDefinition,
  ThemeConfig,
} from "./types";
import { createPublicationPreset } from "./services/publication-style";

const THEME_BG_CLASS = "bg-[var(--ml-bg)]";
const THEME_FG_CLASS = "text-[var(--ml-fg)]";
const THEME_UI_CLASS = "bg-[var(--ml-ui)]";
const THEME_BORDER_CLASS = "border-[var(--ml-border)]";
const THEME_EDITOR_BG_CLASS = "bg-[var(--ml-editor-bg)]";
const THEME_EDITOR_FG_CLASS = "text-[var(--ml-editor-fg)]";
const THEME_ACCENT_CLASS = "text-[var(--ml-accent)]";

export const THEMES: Record<Theme, ThemeConfig> = {
  [Theme.Coffee]: {
    bg: THEME_BG_CLASS,
    bgHex: "#2b231f",
    fg: THEME_FG_CLASS,
    fgHex: "#f8f1e8",
    ui: THEME_UI_CLASS,
    uiHex: "#3a2f29",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#6a5448",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#2b231f",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#f8f1e8",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#f4c68f",
    prose: "prose-invert prose-stone",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Light]: {
    bg: THEME_BG_CLASS,
    bgHex: "#ffffff",
    fg: THEME_FG_CLASS,
    fgHex: "#0f172a",
    ui: THEME_UI_CLASS,
    uiHex: "#f9fafb",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#e5e7eb",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#ffffff",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#0f172a",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#4f46e5",
    prose: "prose-slate",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'Fira Code', 'JetBrains Mono', monospace",
  },
  [Theme.Dark]: {
    bg: THEME_BG_CLASS,
    bgHex: "#16191e",
    fg: THEME_FG_CLASS,
    fgHex: "#f4f4f5",
    ui: THEME_UI_CLASS,
    uiHex: "#1d2229",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#2c3440",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#16191e",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#f4f4f5",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#7dd3fc",
    prose: "prose-invert",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Forest]: {
    bg: THEME_BG_CLASS,
    bgHex: "#17241b",
    fg: THEME_FG_CLASS,
    fgHex: "#e8fbe9",
    ui: THEME_UI_CLASS,
    uiHex: "#203124",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#3c6b48",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#17241b",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#e8fbe9",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#90f0a8",
    prose: "prose-invert prose-green",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'Cascadia Code', 'JetBrains Mono', monospace",
  },
  [Theme.Golden]: {
    bg: THEME_BG_CLASS,
    bgHex: "#f4d49a",
    fg: THEME_FG_CLASS,
    fgHex: "#1e1308",
    ui: THEME_UI_CLASS,
    uiHex: "#e7be73",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#6b4b16",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#f4d49a",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#1e1308",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#2a1808",
    prose: "prose-amber",
    uiFont: "'Merriweather Sans', 'Segoe UI', sans-serif",
    editorFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
  [Theme.Midnight]: {
    bg: THEME_BG_CLASS,
    bgHex: "#111827",
    fg: THEME_FG_CLASS,
    fgHex: "#eef2ff",
    ui: THEME_UI_CLASS,
    uiHex: "#0b1220",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#24344e",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#111827",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#eef2ff",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#8fb5ff",
    prose: "prose-invert prose-indigo",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Neomatrix]: {
    bg: THEME_BG_CLASS,
    bgHex: "#040b04",
    fg: THEME_FG_CLASS,
    fgHex: "#8afcc7",
    ui: THEME_UI_CLASS,
    uiHex: "#061207",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#1b5a33",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#040b04",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#8afcc7",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#57ff9e",
    prose: "prose-invert prose-green",
    uiFont: "'Chakra Petch', 'Segoe UI', sans-serif",
    editorFont: "'Share Tech Mono', 'Cascadia Code', monospace",
  },
  [Theme.Nord]: {
    bg: THEME_BG_CLASS,
    bgHex: "#2E3440",
    fg: THEME_FG_CLASS,
    fgHex: "#ECEFF4",
    ui: THEME_UI_CLASS,
    uiHex: "#262f40",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#425066",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#2E3440",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#ECEFF4",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#88C0D0",
    prose: "prose-invert prose-blue",
    uiFont: "'Source Sans 3', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Sepia]: {
    bg: THEME_BG_CLASS,
    bgHex: "#f2e6c5",
    fg: THEME_FG_CLASS,
    fgHex: "#2d2417",
    ui: THEME_UI_CLASS,
    uiHex: "#e8d7ad",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#b99f63",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#f2e6c5",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#2d2417",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#8d5f12",
    prose: "prose-stone",
    uiFont: "'Merriweather Sans', 'Segoe UI', sans-serif",
    editorFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
  [Theme.Synthwave]: {
    bg: THEME_BG_CLASS,
    bgHex: "#221833",
    fg: THEME_FG_CLASS,
    fgHex: "#fef3ff",
    ui: THEME_UI_CLASS,
    uiHex: "#2e1f45",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#8a39d3",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#221833",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#fef3ff",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#ff89cf",
    prose: "prose-invert prose-pink",
    uiFont: "'Exo 2', 'Segoe UI', sans-serif",
    editorFont: "'JetBrains Mono', 'Fira Code', monospace",
  },
  [Theme.Terminal]: {
    bg: THEME_BG_CLASS,
    bgHex: "#000000",
    fg: THEME_FG_CLASS,
    fgHex: "#87ffa5",
    ui: THEME_UI_CLASS,
    uiHex: "#050505",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#1c4728",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#000000",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#87ffa5",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#5bffa0",
    prose: "prose-invert prose-green",
    uiFont: "'Chakra Petch', 'Segoe UI', sans-serif",
    editorFont: "'Share Tech Mono', 'Cascadia Code', monospace",
  },
  [Theme.Firenight]: {
    bg: THEME_BG_CLASS,
    bgHex: "#1b0f0d",
    fg: THEME_FG_CLASS,
    fgHex: "#ffe1bf",
    ui: THEME_UI_CLASS,
    uiHex: "#2a1713",
    uiBorder: THEME_BORDER_CLASS,
    uiBorderHex: "#8a4c31",
    editorBg: THEME_EDITOR_BG_CLASS,
    editorBgHex: "#1b0f0d",
    editorFg: THEME_EDITOR_FG_CLASS,
    editorFgHex: "#ffe1bf",
    accent: THEME_ACCENT_CLASS,
    accentHex: "#ffb86c",
    prose: "prose-invert prose-amber",
    uiFont: "'Merriweather Sans', 'Segoe UI', sans-serif",
    editorFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
  },
};

export const DEFAULT_THEME_LIBRARY: ThemeDefinition[] = Object.values(Theme).map((themeId) => ({
  id: themeId,
  name: themeId,
  builtIn: true,
  baseThemeId: themeId,
  config: THEMES[themeId],
}));

export function createDefaultThemeLibrary(): ThemeDefinition[] {
  return DEFAULT_THEME_LIBRARY.map((theme) => ({
    ...theme,
    config: { ...theme.config },
  }));
}

export const DEFAULT_SHORTCUTS: Record<string, string> = {
  "file-new": "Ctrl+N",
  "file-open": "Ctrl+O",
  "file-open-folder": "Ctrl+Shift+O",
  "file-save": "Ctrl+S",
  "file-save-as": "Ctrl+Shift+S",
  "file-export": "Ctrl+E",
  "file-print": "Ctrl+P",
  "edit-undo": "Ctrl+Z",
  "edit-redo": "Ctrl+Y",
  "edit-find": "Ctrl+F",
  "edit-replace": "Ctrl+H",
  "edit-snippets": "Ctrl+J",
  "view-edit": "Ctrl+1",
  "view-split": "Ctrl+2",
  "view-preview": "Ctrl+3",
  "view-zen": "F10",
  "view-toolbar": "Ctrl+T",
  "view-sidebar": "Ctrl+B",
  "help-shortcuts": "F1",
  "view-theme-cycle": "Ctrl+Shift+T",
  "app-settings": "Ctrl+,",
  "app-command-palette": "Ctrl+P",
  "fmt-bold": "Ctrl+Shift+B",
  "fmt-italic": "Ctrl+I",
  "fmt-link": "Ctrl+K",
  "fmt-ul": "Ctrl+Shift+8",
  "fmt-ol": "Ctrl+Shift+7",
  "fmt-task": "Ctrl+Shift+9",
};

export const TEXT_PRESETS: Record<string, TextPreset> = {
  minimalist: {
    id: "minimalist",
    name: "Minimalist",
    description: "Clean sans-serif reading style.",
    fontFamily: "sans",
    proseClass: "prose-slate",
    lineHeight: 1.6,
    components: {
      h1: "font-sans font-bold tracking-tight",
      h2: "font-sans font-semibold tracking-tight",
      p: "font-sans leading-relaxed",
      img: "rounded-xl shadow-sm",
      blockquote: "border-l-2 border-slate-300 pl-4 italic",
      code: "rounded-md",
      link: "underline decoration-1 underline-offset-2",
    },
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    description: "Serif-focused long-form layout.",
    fontFamily: "serif",
    proseClass: "prose-stone",
    lineHeight: 1.8,
    components: {
      h1: "font-serif font-bold italic tracking-wide",
      h2: "font-serif font-medium",
      p: "font-serif text-lg leading-loose",
      img: "rounded-sm shadow-md",
      blockquote: "border-l-4 border-stone-400 pl-6 italic font-serif text-xl",
      code: "rounded",
      link: "decoration-2 underline-offset-4",
    },
  },
  technical: {
    id: "technical",
    name: "Technical",
    description: "Documentation-first technical style.",
    fontFamily: "mono",
    proseClass: "prose-neutral",
    lineHeight: 1.5,
    components: {
      h1: "font-mono font-bold uppercase tracking-tighter",
      h2: "font-mono font-bold border-b pb-2",
      p: "font-sans text-base",
      img: "rounded-none border-2 border-gray-200",
      blockquote:
        "bg-gray-100 dark:bg-gray-800 p-4 border-l-4 border-gray-500 not-italic font-mono text-sm",
      code: "rounded-sm border border-gray-200 dark:border-gray-700",
      link: "text-blue-600 dark:text-blue-400 hover:underline",
    },
  },
  creative: {
    id: "creative",
    name: "Creative",
    description: "Expressive display style.",
    fontFamily: "sans",
    proseClass: "prose-pink",
    lineHeight: 1.7,
    components: {
      h1: "font-black uppercase tracking-widest decoration-wavy decoration-pink-500 underline",
      h2: "font-bold tracking-wide text-pink-600 dark:text-pink-400",
      p: "font-medium",
      img: "rounded-[2rem] shadow-xl rotate-1 hover:rotate-0 transition-transform",
      blockquote:
        "border-l-8 border-pink-400 pl-6 font-bold text-lg bg-pink-50 dark:bg-pink-900/20 py-2 rounded-r-xl",
      code: "rounded-xl shadow-inner",
      link: "font-bold hover:text-pink-500 transition-colors",
    },
  },
};

export const PUBLICATION_PRESET_DEFAULTS: PublicationPreset[] = [
  createPublicationPreset(
    "modern",
    "Modern",
    "Layout limpo de produto com contraste alto e ritmo estável.",
    { bg: "#f8fafc", text: "#111827", accent: "#172554", muted: "#475569", border: "rgba(15,23,42,0.14)" },
    {
      fontFamily: "'Source Sans 3', 'Segoe UI', sans-serif",
      lineHeight: 1.68,
      bodySize: 18,
      bodyWeight: 430,
      headingWeight: 780,
      tracking: "normal",
    },
    {
      h1: { size: 46, weight: 820, lineHeight: 1.02, letterSpacing: -0.035, marginTop: 8, marginBottom: 18, tone: "text" },
      h2: { size: 32, weight: 760, lineHeight: 1.08, letterSpacing: -0.025, marginTop: 28, marginBottom: 14, tone: "text" },
      h3: { size: 24, weight: 720, lineHeight: 1.14, letterSpacing: -0.01, marginTop: 22, marginBottom: 10, tone: "accent" },
    },
    { pagePadding: 36, columnWidth: 860, blockGap: 24, paragraphGap: 14 }
  ),
  createPublicationPreset(
    "paper",
    "Paper",
    "Leitura longa com textura editorial e serif mais calma.",
    { bg: "#f6edda", text: "#2f2418", accent: "#5e3a14", muted: "#6b5c4d", border: "rgba(47,36,24,0.16)" },
    {
      fontFamily: "'Merriweather', Georgia, serif",
      lineHeight: 1.86,
      bodySize: 19,
      bodyWeight: 420,
      headingWeight: 760,
      tracking: "normal",
    },
    {
      h1: { size: 44, weight: 780, lineHeight: 1.05, letterSpacing: -0.025, marginTop: 8, marginBottom: 22, tone: "text", italic: true },
      h2: { size: 30, weight: 720, lineHeight: 1.12, letterSpacing: -0.02, marginTop: 30, marginBottom: 16, tone: "text" },
      h3: { size: 22, weight: 700, lineHeight: 1.18, letterSpacing: 0, marginTop: 24, marginBottom: 10, tone: "accent" },
      blockquote: { paddingX: 20, paddingY: 16, radius: 18, borderWidth: 4, tone: "muted", useBackground: true, italic: true },
    },
    { pagePadding: 38, columnWidth: 760, blockGap: 26, paragraphGap: 16 }
  ),
  createPublicationPreset(
    "night",
    "Night",
    "Modo noturno técnico com contraste forte e ritmo controlado.",
    { bg: "#030712", text: "#e2e8f0", accent: "#7dd3fc", muted: "#94a3b8", border: "rgba(226,232,240,0.18)" },
    {
      fontFamily: "'IBM Plex Mono', 'JetBrains Mono', monospace",
      lineHeight: 1.74,
      bodySize: 16,
      bodyWeight: 430,
      headingWeight: 760,
      tracking: "wide",
    },
    {
      h1: { size: 42, weight: 800, lineHeight: 1.04, letterSpacing: 0.05, marginTop: 10, marginBottom: 18, tone: "accent", uppercase: true },
      h2: { size: 28, weight: 760, lineHeight: 1.12, letterSpacing: 0.02, marginTop: 28, marginBottom: 12, tone: "text", uppercase: true },
      h3: { size: 22, weight: 720, lineHeight: 1.18, letterSpacing: 0.01, marginTop: 20, marginBottom: 10, tone: "accent" },
      codeBlock: { fontSize: 14, padding: 18, radius: 16, useBackground: true, useBorder: true },
      image: { radius: 14, margin: 22, useBorder: true, shadow: "soft" },
    },
    { pagePadding: 34, columnWidth: 920, blockGap: 22, paragraphGap: 14 }
  ),
  createPublicationPreset(
    "magazine",
    "Magazine",
    "Visual de revista com títulos largos, respiro e contraste de seções.",
    { bg: "#fff7ed", text: "#1f1b4b", accent: "#312e81", muted: "#6d5bb8", border: "rgba(49,46,129,0.16)" },
    {
      fontFamily: "'Merriweather Sans', 'Segoe UI', sans-serif",
      lineHeight: 1.62,
      bodySize: 18,
      bodyWeight: 440,
      headingWeight: 800,
      tracking: "tight",
    },
    {
      h1: { size: 52, weight: 840, lineHeight: 0.98, letterSpacing: 0.04, marginTop: 8, marginBottom: 18, tone: "text", uppercase: true },
      h2: { size: 30, weight: 760, lineHeight: 1.08, letterSpacing: 0.02, marginTop: 30, marginBottom: 12, tone: "accent", uppercase: true },
      h3: { size: 22, weight: 740, lineHeight: 1.16, letterSpacing: 0.01, marginTop: 22, marginBottom: 10, tone: "accent" },
      table: { headerWeight: 760, cellPaddingX: 16, cellPaddingY: 10, radius: 16, striped: true, dense: false, useBorder: true, captionTone: "accent" },
      image: { radius: 22, margin: 24, useBorder: false, shadow: "lifted" },
    },
    { pagePadding: 34, columnWidth: 980, blockGap: 24, paragraphGap: 12 }
  ),
];

export const DEFAULT_SETTINGS: AppSettings = {
  language: "pt-BR",
  fontSize: 16,
  lineHeight: 1.6,
  fontFamily: "mono",
  wordWrap: true,
  typewriterMode: false,
  spellCheck: true,
  singleInstance: true,
  autoSave: true,
  autoSaveInterval: 60,
  focusMode: false,
  customShortcuts: DEFAULT_SHORTCUTS,
  presetId: "minimalist",
  publicationPresetId: "modern",
  toolbarPosition: "bottom",
  themeLibrary: createDefaultThemeLibrary(),
  theme: Theme.Golden,
  viewMode: "edit",
  chromeMode: "unified",
  tabsEnabled: true,
  sidebarEnabled: true,
  sidebarWidth: 260,
  floatingToolbarAnchor: "bottom",
  showToolbarSectionLabels: true,
  toolbarAlwaysShowIcons: true,
  toolbarCompactBreakpoint: 560,
  toolbarDisplayMode: "icon_text",
  toolbarSectionBehavior: "default",
  toolbarSections: {
    files: true,
    system: true,
    editing: true,
  },
  toolbarItems: {
    fileNew: false,
    fileOpen: true,
    fileOpenFolder: true,
    fileSave: true,
    fileExport: true,
    sysFind: true,
    sysSnippets: true,
    sysTheme: true,
    sysSidebar: true,
    sysEdit: true,
    sysSplit: true,
    sysPreview: true,
    sysZen: true,
    sysSettings: true,
    editBold: true,
    editItalic: true,
    editCode: true,
    editLink: true,
    editImage: true,
    editUL: true,
    editOL: true,
    editTask: true,
  },
  toolbarByAnchor: {
    top: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
    bottom: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
    left: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
    right: {
      showToolbarSectionLabels: true,
      toolbarCompactBreakpoint: 560,
      toolbarDisplayMode: "icon_text",
      toolbarSectionBehavior: "default",
      toolbarSections: {
        files: true,
        system: true,
        editing: true,
      },
      toolbarItems: {
        fileNew: false,
        fileOpen: true,
        fileOpenFolder: true,
        fileSave: true,
        fileExport: true,
        sysFind: true,
        sysSnippets: true,
        sysTheme: true,
        sysSidebar: true,
        sysEdit: true,
        sysSplit: true,
        sysPreview: true,
        sysZen: true,
        sysSettings: true,
        editBold: true,
        editItalic: true,
        editCode: true,
        editLink: true,
        editImage: true,
        editUL: true,
        editOL: true,
        editTask: true,
      },
    },
  },
  accordionState: {
    interface: true,
    themes: true,
    toolbar: true,
    behavior: true,
    typography: true,
    shortcuts: false,
    presets: false,
  },
  findReplace: {
    caseSensitive: false,
    wholeWord: false,
    useRegex: false,
  },
  commandPalette: {
    includeActions: true,
    includeOpenTabs: true,
    includeRecentFiles: true,
    includeSnippets: true,
    searchMode: "standard",
    snippetBehavior: "insert",
    closeAfterSelect: true,
    showHints: true,
    maxResults: 18,
  },
};

export const INITIAL_MARKDOWN = `# Mark-Lee

Bem-vindo ao Mark-Lee. Este editor foi atualizado para fluxo com abas, workspace e exportação unificada.

## Comece por aqui

- Abra uma pasta no sidebar para navegar no projeto
- Use \`Ctrl+F\` para buscar/substituir com mais opções
- Exporte seu conteúdo pelo menu único de exportação
`;

export const SNIPPETS: Snippet[] = [
  {
    id: "dev-table",
    name: "Tabela Markdown",
    category: "dev",
    trigger: "tabela",
    icon: "TB",
    content: "| Header 1 | Header 2 |\n|----------|----------|\n| Cell 1   | Cell 2   |",
  },
  {
    id: "dev-code",
    name: "Bloco TypeScript",
    category: "dev",
    trigger: "codigo_ts",
    icon: "CD",
    content: "```ts\n// your code\n```",
  },
  {
    id: "frontend-react-card",
    name: "Componente React Card",
    category: "frontend",
    trigger: "react_card",
    icon: "FE",
    content:
      "```tsx\ntype CardProps = { title: string; body: string };\n\nexport function Card({ title, body }: CardProps) {\n  return (\n    <article className=\"rounded-xl border p-4 shadow-sm\">\n      <h2 className=\"text-lg font-semibold\">{title}</h2>\n      <p className=\"mt-2 text-sm\">{body}</p>\n    </article>\n  );\n}\n```",
  },
  {
    id: "backend-node-endpoint",
    name: "Endpoint Node/Express",
    category: "backend",
    trigger: "endpoint_node",
    icon: "BE",
    content:
      "```ts\nimport { Router } from \"express\";\n\nconst router = Router();\n\nrouter.get(\"/health\", (_req, res) => {\n  res.json({ ok: true, ts: Date.now() });\n});\n\nexport default router;\n```",
  },
  {
    id: "macro-meeting-notes",
    name: "Macro Reuniao",
    category: "macro",
    trigger: "reuniao",
    icon: "MC",
    content:
      "## Reuniao - {{data}}\n\n### Participantes\n- \n\n### Decisoes\n- \n\n### Proximos passos\n- [ ] \n",
  },
  {
    id: "php-class",
    name: "Classe PHP",
    category: "php",
    trigger: "php_classe",
    icon: "PH",
    content:
      "```php\n<?php\n\ndeclare(strict_types=1);\n\nfinal class UserService\n{\n    public function findById(int $id): array\n    {\n        return ['id' => $id, 'name' => 'Mark'];\n    }\n}\n```",
  },
  {
    id: "java-service",
    name: "Service Java",
    category: "java",
    trigger: "java_service",
    icon: "JV",
    content:
      "```java\npublic class UserService {\n  public String health() {\n    return \"ok\";\n  }\n}\n```",
  },
  {
    id: "python-dataclass",
    name: "Dataclass Python",
    category: "python",
    trigger: "python_dataclass",
    icon: "PY",
    content:
      "```python\nfrom dataclasses import dataclass\n\n@dataclass(slots=True)\nclass Person:\n    name: str\n    email: str\n```",
  },
  {
    id: "editorial-article-structure",
    name: "Estrutura Editorial",
    category: "editorial",
    trigger: "editorial_artigo",
    icon: "ED",
    content:
      "# Titulo\n\n## Gancho\n\n## Contexto\n\n## Argumento principal\n\n## Fechamento\n",
  },
  {
    id: "shopping-list",
    name: "Lista de Compras",
    category: "lista_compras",
    trigger: "lista_compras",
    icon: "LC",
    content:
      "## Lista de compras\n\n- [ ] Arroz\n- [ ] Feijao\n- [ ] Cafe\n- [ ] Leite\n- [ ] Frutas\n",
  },
  {
    id: "dados-pessoais",
    name: "Dados Pessoais",
    category: "dados_pessoais",
    trigger: "dados_pessoais",
    icon: "DP",
    content:
      "Nome completo: \nData de nascimento: \nCPF: \nRG: \nEndereco: \nCidade/UF: \nCEP: \n",
  },
  {
    id: "contato-card",
    name: "Contato",
    category: "contato",
    trigger: "contato",
    icon: "CT",
    content:
      "Nome: \nEmpresa: \nCargo: \nEmail: \nTelefone: \nLinkedIn: \n",
  },
  {
    id: "task",
    name: "Task List",
    category: "dev",
    trigger: "tarefas",
    icon: "TS",
    content: "- [ ] Task 1\n- [ ] Task 2\n- [x] Done",
  },
  {
    id: "callout",
    name: "Callout",
    category: "editorial",
    trigger: "chamada",
    icon: "NT",
    content: "> **Note:** Important information here.",
  },
  {
    id: "image",
    name: "Image",
    category: "frontend",
    trigger: "imagem_md",
    icon: "IM",
    content: "![Alt text](./image.png)",
  },
  {
    id: "link",
    name: "Link",
    category: "dev",
    trigger: "link_md",
    icon: "LK",
    content: "[Link text](https://example.com)",
  },
];
